#!/usr/bin/env bash
set -x
set -e
# This module enables the raspicam
echo "# enable raspicam" >> /boot/config.txt
echo "start_x=1" >> /boot/config.txt
echo "gpu_mem=64" >> /boot/config.txt
echo "dtoverlay=disable-bt" >> /boot/config.txt
